Mutation + inversion
Evolutionary-Computation-PK/classical-genetic-algorithm pull request #12
Opened 2024-10-28 15:17 UTC by jakubszpilowski

- poprawione metody mutacji i inwersji
- dodane testy metod mutacji i inwersji

2024-10-30 19:24 UTC, Eve0028 requested changes
Nie jestem w sumie jeszcze do boundary mutation. Ale poprosze tylko małą zmianę w inwersji i testach :-)

2024-10-30 19:24 UTC, Eve0028 commented on source/inversion/inversion.py
> +                        chromosome[gene] = abs(1 - chromosome[gene])
W inwersji ma być bodajże odwrócenie całego łańcucha genów (reverse) i podstawienie go w to miejsce. Np. [0,0,1,0] -> [0,1,0,0]

2024-10-30 19:24 UTC, Eve0028 commented on tests/mutation/test_one_point_mutation.py
> +def test_one_point_mutation_one_chromosome_min_probability():
Mimo wszystko prawdopodobieństwo 0.5 nie zapewnia, że jakiś gen się zmieni :D

2024-10-30 19:24 UTC, Eve0028 commented on tests/mutation/test_two_point_mutation.py
> +def test_one_point_mutation_one_chromosome_min_probability():
Prawdopodobieństwo 0.5 nie zapewnia, że jakikolwiek gen się zmieni. Ale może odpuśćmy sobie testowanie 'probabilistyczne'. Ewentualnie może zastosujemy jakiś konkretny seed, ale to jak starczy czasu może

2024-10-30 21:15 UTC, Eve0028 commented on source/mutation/mutation.py
> +class Mutation:
Myślę, że mutation_probablity można dodać do konstruktora Mutation

2024-10-30 21:17 UTC, jakubszpilowski commented
Oki, to:
- usuwam te testy probabilistyczne
- poprawiam inwersje - źle zrozumiałem mechanizm działania
- dodam parametr do konstruktora klasy

2024-10-30 21:18 UTC, jakubszpilowski commented
Mutacja brzegowa jest w porządku?

2024-10-31 16:37 UTC, jakubszpilowski commented
Poprawione
Usunąłem te testy probabilistyczne, dla inwersji nie wymyśliłem niczego szczególnego, ale szkoda tracić czas na pisanie testów na razie

2024-11-04 21:07 UTC, Eve0028 approved these changes

2024-11-04 21:07 UTC, merged